comment:
  behavior: default
  layout: reach,diff,files,footer
  require_changes: false
coverage:
  precision: 2
  range:
  - 40.0
  - 70.0
  round: down
  status:
    project:
      default:
        threshold: 5%
        informational: true
    patch:
      default:
        informational: true
