name: Build
on: pull_request

jobs:
  build:
    name: Builder
    runs-on: ubuntu-latest
    steps:
      #Check out active branch
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      #Cache library files to improve build time
      - name: Cache
        uses: actions/cache@v2
        with:
          path: /Library/
          key: Library-Yomi-StandaloneWindows
          restore-keys: |
              Library-Yomi-
              Library-

      # Build
      - name: Unity - Builder
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{secrets.UNITY_EMAIL}}
          UNITY_PASSWORD: ${{secrets.UNITY_PASSWORD}}
        with:
          targetPlatform: StandaloneWindows
  test:
    name: Test Runner
    runs-on: ubuntu-latest
    steps:
      #Check out active branch
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      #Cache library files to improve build time
      - name: Cache
        uses: actions/cache@v2
        with:
          path: /Library/
          key: Library-Yomi-StandaloneWindows
          restore-keys: |
              Library-Yomi-
              Library-
      
      # Test Runner
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2021.3.20f1
          testMode: All
          customParameters: |
            -debugCodeOptimization 
            -enableCodeCoverage 

      # CodeCov integration
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: automated
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage-results/**/*.xml
