name: Build
on: 
  pull_request:
    branches: main
  push:
    branches: main

jobs:
  build:
    name: Builder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Cache
        uses: actions/cache@v2
        with:
          path: /Library/
          key: Library-Yomi-StandaloneWindows
          restore-keys: |
              Library-Yomi-
              Library-
      - name: Unity - Builder
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{secrets.UNITY_EMAIL}}
          UNITY_PASSWORD: ${{secrets.UNITY_PASSWORD}}
        with:
          targetPlatform: StandaloneWindows
  test:
    name: Test Runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Cache
        uses: actions/cache@v2
        with:
          path: /Library/
          key: Library-Yomi-StandaloneWindows
          restore-keys: |
              Library-Yomi-
              Library-
      - name: Run tests
        id: testStep
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2021.3.20f1
          coverageOptions: 'assemblyFilters:+_ProjectYomi'
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: CodeCoverage/**/*.xml 
